- name: Check for the carcinogenesis directory
  stat:
    path: "{{ target_dir }}/datasets/carcinogenesis"
  register: dataset_dir

- block:
  - name: Create dataset directory 
    file:
      path: "{{ target_dir }}/datasets/carcinogenesis/"
      state: directory

  - name: Create a temporary download directory
    tempfile:
      state: directory
      suffix: carcinogenesis
    register: tempdir

  - name: Download the dataset
    get_url:
      url: "https://www.dropbox.com/s/v14bhrf1x235wu1/carcinogenesis.zip?dl=1"
      dest: "{{ tempdir.path }}/carcinogenesis.zip"

  - name: Unzip dataset and queries
    unarchive:
      remote_src: yes
      src: "{{ tempdir.path }}/carcinogenesis.zip"
      dest: "{{ target_dir }}/datasets/carcinogenesis/"
  when: not dataset_dir.stat.exists
