iguana_http_connections:
  - number: 1

iguana_query_mixes_limit: 5
iguana_query_timeout: 300000
systems_http:
  - name: fuseki
    connection_url: http://localhost:3030/%d/sparql
  - name: virtuoso
    connection_url: http://localhost:8890/sparql
  - name: graphdb
    connection_url: http://localhost:7200/repositories/%d
  - name: blazegraph
    connection_url: http://localhost:9999/blazegraph/sparql